name: Deploy to EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_KEY }}
          command_timeout: 30m
          script: |
            set -e

            APP_DIR=~/py-fastapi-homework-5-ec2-deploy-task
            cd $APP_DIR

            echo "Pull latest code..."
            git fetch origin
            git reset --hard origin/main

            echo "Stop old stack (safe)..."
            docker compose -f docker-compose-prod.yml down --remove-orphans || true

            echo "Start containers (FAST MODE)..."
            docker compose -f docker-compose-prod.yml up -d

            echo "Cleanup unused images..."
            docker image prune -f

            echo "DONE 🚀"
