name: Deploy to EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_KEY }}
          command_timeout: 30m
          script: |
            set -e

            APP_DIR=~/py-fastapi-homework-5-ec2-deploy-task
            cd $APP_DIR

            echo "Pull latest code..."
            git fetch origin
            git reset --hard origin/main

            echo "FAST CLEAN (only compose stack)..."
            docker compose -f docker-compose-prod.yml down --remove-orphans || true

            echo "Removing leftover project containers (fix conflicts)..."
            docker ps -a --filter "name=theater" -q | xargs -r docker rm -f || true

            echo "Starting containers (NO BUILD - FAST MODE)..."
            docker compose -f docker-compose-prod.yml up -d

            echo "Cleaning unused images..."
            docker image prune -f

            echo "DONE 🚀"
